# Generated by Django 5.2 on 2025-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reset_password_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset', 'Password Reset'), ('form_generated', 'Form Generated'), ('client_added', 'Client Added'), ('client_updated', 'Client Updated'), ('client_exported', 'Client Data Exported'), ('llm_extraction', 'LLM Data Extraction')], max_length=64),
        ),
    ]
