# Generated by Django 5.1 on 2025-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokercompany',
            options={'ordering': ['name'], 'verbose_name': 'Broker Company', 'verbose_name_plural': 'Broker Companies'},
        ),
        migrations.RemoveField(
            model_name='brokercompany',
            name='code',
        ),
        migrations.RemoveField(
            model_name='brokercompany',
            name='id',
        ),
        migrations.AddField(
            model_name='brokercompany',
            name='address',
            field=models.TextField(default='Hong Kong'),
        ),
        migrations.AddField(
            model_name='brokercompany',
            name='contact_email',
            field=models.EmailField(default='contact@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='brokercompany',
            name='ia_reg_code',
            field=models.CharField(default='IA12313123', help_text='IA Registration Code', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokercompany',
            name='mpfa_reg_code',
            field=models.CharField(default='MPFA123123', help_text='MPFA Registration Code', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokercompany',
            name='phone_number',
            field=models.CharField(default='+852 1234 5678', max_length=20),
        ),
        migrations.AddField(
            model_name='brokercompany',
            name='responsible_person_email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='brokercompany',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
