# Generated by Django 5.1 on 2025-04-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_brokercompany_options_and_more'),
    ]

    operations = [
    ]
