# Generated by Django 5.1 on 2025-04-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_mpa_code_to_mpfa_reg_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokercompany',
            options={'ordering': ['name'], 'verbose_name': 'Broker Company', 'verbose_name_plural': 'Broker Companies'},
        ),
    ]
