# Generated by Django 4.2.20 on 2025-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_first_n_5c6577_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='monthly_expenses',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='client',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_period',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_residency',
        ),
        migrations.RemoveField(
            model_name='client',
            name='work_address',
        ),
        migrations.AddField(
            model_name='client',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
