# Generated by Django 5.1 on 2025-04-06 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldmapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formfieldmapping',
            name='field_definition_override',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formfieldmapping',
            name='transformation_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formfieldmapping',
            name='validation_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='form_affiliation',
            field=models.CharField(choices=[('broker', 'Broker'), ('insurance', 'Insurance Company')], default='broker', max_length=20),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(choices=[('fna', 'Financial Needs Analysis'), ('application', 'Application Form'), ('agreement', 'Agreement'), ('payment', 'Payment Form')], default='application', max_length=20),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.CreateModel(
            name='FormSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_sets', to=settings.AUTH_USER_MODEL)),
                ('forms', models.ManyToManyField(related_name='form_sets', to='pdf_forms.formtemplate')),
            ],
            options={
                'verbose_name': 'form set',
                'verbose_name_plural': 'form sets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandardizedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', max_length=20)),
                ('field_category', models.CharField(choices=[('client', 'Client Standardized Field'), ('broker', 'Broker-Specific Field'), ('user', 'User-Specific Field')], default='client', max_length=20)),
                ('validation_rules', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('field_definition', models.TextField(blank=True)),
                ('llm_guide', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_standardized_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'standardized field',
                'verbose_name_plural': 'standardized fields',
                'ordering': ['field_category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='formfieldmapping',
            name='standardized_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_mappings', to='pdf_forms.standardizedfield'),
        ),
    ]
