# Generated by Django 5.1 on 2025-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0002_formfieldmapping_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedfield',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='relationships',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='validation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
