# Generated by Django 5.1 on 2025-04-06 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0003_standardizedfield_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedFieldCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'standardized field category',
                'verbose_name_plural': 'standardized field categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standardized_fields', to='pdf_forms.standardizedfieldcategory'),
        ),
    ]
