# Generated by Django 5.1 on 2025-04-06 16:06

from django.db import migrations

def add_initial_categories(apps, schema_editor):
    StandardizedFieldCategory = apps.get_model('pdf_forms', 'StandardizedFieldCategory')
    
    categories = [
        {
            'name': 'Personal Information',
            'description': 'Fields related to personal information such as name, date of birth, etc.'
        },
        {
            'name': 'Contact Information',
            'description': 'Fields related to contact information such as email, phone, address, etc.'
        }
    ]
    
    for category in categories:
        StandardizedFieldCategory.objects.create(**category)

def remove_initial_categories(apps, schema_editor):
    StandardizedFieldCategory = apps.get_model('pdf_forms', 'StandardizedFieldCategory')
    StandardizedFieldCategory.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('pdf_forms', '0004_standardizedfieldcategory_standardizedfield_category'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories, remove_initial_categories),
    ]
