# Generated by Django 5.1 on 2025-04-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0002_add_default_standardized_field_categories'),
        ('pdf_forms', '0005_add_initial_categories'),
    ]

    operations = [
    ]
