# Generated by Django 5.1 on 2025-04-07 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0008_remove_standardizedfield_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardizedfield',
            options={'ordering': ['field_category', 'display_category', 'name']},
        ),
        migrations.RemoveField(
            model_name='standardizedfield',
            name='description',
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='default_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='display_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='field_category',
            field=models.CharField(choices=[('client', 'Client'), ('account', 'Account'), ('beneficiary', 'Beneficiary'), ('document', 'Document'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='field_definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone'), ('ssn', 'SSN'), ('address', 'Address'), ('signature', 'Signature')], max_length=50),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='llm_guide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardizedfield',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='standardizedfield',
            index=models.Index(fields=['name'], name='pdf_forms_s_name_b4a75a_idx'),
        ),
        migrations.AddIndex(
            model_name='standardizedfield',
            index=models.Index(fields=['field_category'], name='pdf_forms_s_field_c_668882_idx'),
        ),
        migrations.AddIndex(
            model_name='standardizedfield',
            index=models.Index(fields=['display_category'], name='pdf_forms_s_display_4dfc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='standardizedfield',
            index=models.Index(fields=['is_active'], name='pdf_forms_s_is_acti_bbb39b_idx'),
        ),
    ]
