# Generated by Django 4.2.20 on 2025-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0010_import_standardized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedfield',
            name='display_order',
            field=models.IntegerField(default=100, help_text='Order to display this field in forms and listings'),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='is_client_field',
            field=models.BooleanField(default=False, help_text='Whether this field should be stored in client data'),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='is_core_field',
            field=models.BooleanField(default=False, help_text='Whether this is a core field shown in client listings'),
        ),
        migrations.AddField(
            model_name='standardizedfield',
            name='is_filterable',
            field=models.BooleanField(default=False, help_text='Whether this field can be used for filtering clients'),
        ),
    ]
